// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/tiledb.h"
#include <Rcpp.h>

using namespace Rcpp;

// tiledb_version
NumericVector tiledb_version();
RcppExport SEXP _tiledb_tiledb_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    rcpp_result_gen = Rcpp::wrap(tiledb_version());
    return rcpp_result_gen;
END_RCPP
}
// tiledb_ctx
XPtr<tiledb::Context> tiledb_ctx();
RcppExport SEXP _tiledb_tiledb_ctx() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    rcpp_result_gen = Rcpp::wrap(tiledb_ctx());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tiledb_tiledb_version", (DL_FUNC) &_tiledb_tiledb_version, 0},
    {"_tiledb_tiledb_ctx", (DL_FUNC) &_tiledb_tiledb_ctx, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_tiledb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
