// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/tiledb.h"
#include <Rcpp.h>

using namespace Rcpp;

// tiledb_datatype_R_type
std::string tiledb_datatype_R_type(std::string datatype);
RcppExport SEXP _tiledb_tiledb_datatype_R_type(SEXP datatypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type datatype(datatypeSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_datatype_R_type(datatype));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_version
NumericVector libtiledb_version();
RcppExport SEXP _tiledb_libtiledb_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(libtiledb_version());
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_ctx
XPtr<tiledb::Context> libtiledb_ctx(Nullable<XPtr<tiledb::Config>> config);
RcppExport SEXP _tiledb_libtiledb_ctx(SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Nullable<XPtr<tiledb::Config>> >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_ctx(config));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_config_save_to_file
std::string libtiledb_config_save_to_file(XPtr<tiledb::Config> config, std::string filename);
RcppExport SEXP _tiledb_libtiledb_config_save_to_file(SEXP configSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Config> >::type config(configSEXP);
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_config_save_to_file(config, filename));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_config_load_from_file
XPtr<tiledb::Config> libtiledb_config_load_from_file(std::string filename);
RcppExport SEXP _tiledb_libtiledb_config_load_from_file(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_config_load_from_file(filename));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_ctx_config
XPtr<tiledb::Config> libtiledb_ctx_config(XPtr<tiledb::Context> ctx);
RcppExport SEXP _tiledb_libtiledb_ctx_config(SEXP ctxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Context> >::type ctx(ctxSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_ctx_config(ctx));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_ctx_is_supported_fs
bool libtiledb_ctx_is_supported_fs(XPtr<tiledb::Context> ctx, std::string scheme);
RcppExport SEXP _tiledb_libtiledb_ctx_is_supported_fs(SEXP ctxSEXP, SEXP schemeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Context> >::type ctx(ctxSEXP);
    Rcpp::traits::input_parameter< std::string >::type scheme(schemeSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_ctx_is_supported_fs(ctx, scheme));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_config
XPtr<tiledb::Config> libtiledb_config(Nullable<CharacterVector> config);
RcppExport SEXP _tiledb_libtiledb_config(SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_config(config));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_config_vector
CharacterVector libtiledb_config_vector(XPtr<tiledb::Config> config);
RcppExport SEXP _tiledb_libtiledb_config_vector(SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Config> >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_config_vector(config));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_config_set
XPtr<tiledb::Config> libtiledb_config_set(XPtr<tiledb::Config> config, std::string param, std::string value);
RcppExport SEXP _tiledb_libtiledb_config_set(SEXP configSEXP, SEXP paramSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Config> >::type config(configSEXP);
    Rcpp::traits::input_parameter< std::string >::type param(paramSEXP);
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_config_set(config, param, value));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_config_get
CharacterVector libtiledb_config_get(XPtr<tiledb::Config> config, CharacterVector params);
RcppExport SEXP _tiledb_libtiledb_config_get(SEXP configSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Config> >::type config(configSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_config_get(config, params));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_config_dump
void libtiledb_config_dump(XPtr<tiledb::Config> config);
RcppExport SEXP _tiledb_libtiledb_config_dump(SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Config> >::type config(configSEXP);
    libtiledb_config_dump(config);
    return R_NilValue;
END_RCPP
}
// libtiledb_dim
XPtr<tiledb::Dimension> libtiledb_dim(XPtr<tiledb::Context> ctx, std::string name, std::string type, SEXP domain, SEXP tile_extent);
RcppExport SEXP _tiledb_libtiledb_dim(SEXP ctxSEXP, SEXP nameSEXP, SEXP typeSEXP, SEXP domainSEXP, SEXP tile_extentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Context> >::type ctx(ctxSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type domain(domainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tile_extent(tile_extentSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_dim(ctx, name, type, domain, tile_extent));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_dim_name
std::string libtiledb_dim_name(XPtr<tiledb::Dimension> dim);
RcppExport SEXP _tiledb_libtiledb_dim_name(SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Dimension> >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_dim_name(dim));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_dim_domain
SEXP libtiledb_dim_domain(XPtr<tiledb::Dimension> dim);
RcppExport SEXP _tiledb_libtiledb_dim_domain(SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Dimension> >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_dim_domain(dim));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_dim_tile_extent
SEXP libtiledb_dim_tile_extent(XPtr<tiledb::Dimension> dim);
RcppExport SEXP _tiledb_libtiledb_dim_tile_extent(SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Dimension> >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_dim_tile_extent(dim));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_dim_datatype
std::string libtiledb_dim_datatype(XPtr<tiledb::Dimension> dim);
RcppExport SEXP _tiledb_libtiledb_dim_datatype(SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Dimension> >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_dim_datatype(dim));
    return rcpp_result_gen;
END_RCPP
}
// dim_domain_subarray
NumericVector dim_domain_subarray(NumericVector domain, NumericVector subscript);
RcppExport SEXP _tiledb_dim_domain_subarray(SEXP domainSEXP, SEXP subscriptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type domain(domainSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type subscript(subscriptSEXP);
    rcpp_result_gen = Rcpp::wrap(dim_domain_subarray(domain, subscript));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_domain
XPtr<tiledb::Domain> libtiledb_domain(XPtr<tiledb::Context> ctx, List dims);
RcppExport SEXP _tiledb_libtiledb_domain(SEXP ctxSEXP, SEXP dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Context> >::type ctx(ctxSEXP);
    Rcpp::traits::input_parameter< List >::type dims(dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_domain(ctx, dims));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_domain_ndim
IntegerVector libtiledb_domain_ndim(XPtr<tiledb::Domain> domain);
RcppExport SEXP _tiledb_libtiledb_domain_ndim(SEXP domainSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Domain> >::type domain(domainSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_domain_ndim(domain));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_domain_dimensions
List libtiledb_domain_dimensions(XPtr<tiledb::Domain> domain);
RcppExport SEXP _tiledb_libtiledb_domain_dimensions(SEXP domainSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Domain> >::type domain(domainSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_domain_dimensions(domain));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_domain_datatype
std::string libtiledb_domain_datatype(XPtr<tiledb::Domain> domain);
RcppExport SEXP _tiledb_libtiledb_domain_datatype(SEXP domainSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Domain> >::type domain(domainSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_domain_datatype(domain));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_domain_dump
void libtiledb_domain_dump(XPtr<tiledb::Domain> domain);
RcppExport SEXP _tiledb_libtiledb_domain_dump(SEXP domainSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Domain> >::type domain(domainSEXP);
    libtiledb_domain_dump(domain);
    return R_NilValue;
END_RCPP
}
// libtiledb_compressor
XPtr<tiledb::Compressor> libtiledb_compressor(std::string compressor, int level);
RcppExport SEXP _tiledb_libtiledb_compressor(SEXP compressorSEXP, SEXP levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type compressor(compressorSEXP);
    Rcpp::traits::input_parameter< int >::type level(levelSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_compressor(compressor, level));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_compressor_type
std::string libtiledb_compressor_type(XPtr<tiledb::Compressor> compressor);
RcppExport SEXP _tiledb_libtiledb_compressor_type(SEXP compressorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Compressor> >::type compressor(compressorSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_compressor_type(compressor));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_compressor_level
int libtiledb_compressor_level(XPtr<tiledb::Compressor> compressor);
RcppExport SEXP _tiledb_libtiledb_compressor_level(SEXP compressorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Compressor> >::type compressor(compressorSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_compressor_level(compressor));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_attr
XPtr<tiledb::Attribute> libtiledb_attr(XPtr<tiledb::Context> ctx, std::string name, std::string type, XPtr<tiledb::Compressor> compressor, int ncells);
RcppExport SEXP _tiledb_libtiledb_attr(SEXP ctxSEXP, SEXP nameSEXP, SEXP typeSEXP, SEXP compressorSEXP, SEXP ncellsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Context> >::type ctx(ctxSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< XPtr<tiledb::Compressor> >::type compressor(compressorSEXP);
    Rcpp::traits::input_parameter< int >::type ncells(ncellsSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_attr(ctx, name, type, compressor, ncells));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_attr_name
std::string libtiledb_attr_name(XPtr<tiledb::Attribute> attr);
RcppExport SEXP _tiledb_libtiledb_attr_name(SEXP attrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Attribute> >::type attr(attrSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_attr_name(attr));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_attr_datatype
std::string libtiledb_attr_datatype(XPtr<tiledb::Attribute> attr);
RcppExport SEXP _tiledb_libtiledb_attr_datatype(SEXP attrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Attribute> >::type attr(attrSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_attr_datatype(attr));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_attr_compressor
XPtr<tiledb::Compressor> libtiledb_attr_compressor(XPtr<tiledb::Attribute> attr);
RcppExport SEXP _tiledb_libtiledb_attr_compressor(SEXP attrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Attribute> >::type attr(attrSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_attr_compressor(attr));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_attr_ncells
int libtiledb_attr_ncells(XPtr<tiledb::Attribute> attr);
RcppExport SEXP _tiledb_libtiledb_attr_ncells(SEXP attrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Attribute> >::type attr(attrSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_attr_ncells(attr));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_attr_dump
void libtiledb_attr_dump(XPtr<tiledb::Attribute> attr);
RcppExport SEXP _tiledb_libtiledb_attr_dump(SEXP attrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Attribute> >::type attr(attrSEXP);
    libtiledb_attr_dump(attr);
    return R_NilValue;
END_RCPP
}
// libtiledb_array_schema
XPtr<tiledb::ArraySchema> libtiledb_array_schema(XPtr<tiledb::Context> ctx, XPtr<tiledb::Domain> domain, List attributes, std::string cell_order, std::string tile_order, Nullable<XPtr<tiledb::Compressor>> coords_compressor, Nullable<XPtr<tiledb::Compressor>> offsets_compressor, bool sparse);
RcppExport SEXP _tiledb_libtiledb_array_schema(SEXP ctxSEXP, SEXP domainSEXP, SEXP attributesSEXP, SEXP cell_orderSEXP, SEXP tile_orderSEXP, SEXP coords_compressorSEXP, SEXP offsets_compressorSEXP, SEXP sparseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Context> >::type ctx(ctxSEXP);
    Rcpp::traits::input_parameter< XPtr<tiledb::Domain> >::type domain(domainSEXP);
    Rcpp::traits::input_parameter< List >::type attributes(attributesSEXP);
    Rcpp::traits::input_parameter< std::string >::type cell_order(cell_orderSEXP);
    Rcpp::traits::input_parameter< std::string >::type tile_order(tile_orderSEXP);
    Rcpp::traits::input_parameter< Nullable<XPtr<tiledb::Compressor>> >::type coords_compressor(coords_compressorSEXP);
    Rcpp::traits::input_parameter< Nullable<XPtr<tiledb::Compressor>> >::type offsets_compressor(offsets_compressorSEXP);
    Rcpp::traits::input_parameter< bool >::type sparse(sparseSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_schema(ctx, domain, attributes, cell_order, tile_order, coords_compressor, offsets_compressor, sparse));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_schema_domain
XPtr<tiledb::Domain> libtiledb_array_schema_domain(XPtr<tiledb::ArraySchema> schema);
RcppExport SEXP _tiledb_libtiledb_array_schema_domain(SEXP schemaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::ArraySchema> >::type schema(schemaSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_schema_domain(schema));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_schema_attributes
List libtiledb_array_schema_attributes(XPtr<tiledb::ArraySchema> schema);
RcppExport SEXP _tiledb_libtiledb_array_schema_attributes(SEXP schemaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::ArraySchema> >::type schema(schemaSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_schema_attributes(schema));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_schema_cell_order
std::string libtiledb_array_schema_cell_order(XPtr<tiledb::ArraySchema> schema);
RcppExport SEXP _tiledb_libtiledb_array_schema_cell_order(SEXP schemaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::ArraySchema> >::type schema(schemaSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_schema_cell_order(schema));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_schema_tile_order
std::string libtiledb_array_schema_tile_order(XPtr<tiledb::ArraySchema> schema);
RcppExport SEXP _tiledb_libtiledb_array_schema_tile_order(SEXP schemaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::ArraySchema> >::type schema(schemaSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_schema_tile_order(schema));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_schema_coords_compressor
XPtr<tiledb::Compressor> libtiledb_array_schema_coords_compressor(XPtr<tiledb::ArraySchema> schema);
RcppExport SEXP _tiledb_libtiledb_array_schema_coords_compressor(SEXP schemaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::ArraySchema> >::type schema(schemaSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_schema_coords_compressor(schema));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_schema_offsets_compressor
XPtr<tiledb::Compressor> libtiledb_array_schema_offsets_compressor(XPtr<tiledb::ArraySchema> schema);
RcppExport SEXP _tiledb_libtiledb_array_schema_offsets_compressor(SEXP schemaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::ArraySchema> >::type schema(schemaSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_schema_offsets_compressor(schema));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_schema_sparse
bool libtiledb_array_schema_sparse(XPtr<tiledb::ArraySchema> schema);
RcppExport SEXP _tiledb_libtiledb_array_schema_sparse(SEXP schemaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::ArraySchema> >::type schema(schemaSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_schema_sparse(schema));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_schema_load
XPtr<tiledb::ArraySchema> libtiledb_array_schema_load(XPtr<tiledb::Context> ctx, std::string uri);
RcppExport SEXP _tiledb_libtiledb_array_schema_load(SEXP ctxSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Context> >::type ctx(ctxSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_schema_load(ctx, uri));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_schema_dump
void libtiledb_array_schema_dump(XPtr<tiledb::ArraySchema> schema);
RcppExport SEXP _tiledb_libtiledb_array_schema_dump(SEXP schemaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::ArraySchema> >::type schema(schemaSEXP);
    libtiledb_array_schema_dump(schema);
    return R_NilValue;
END_RCPP
}
// libtiledb_array_create
std::string libtiledb_array_create(std::string uri, XPtr<tiledb::ArraySchema> schema);
RcppExport SEXP _tiledb_libtiledb_array_create(SEXP uriSEXP, SEXP schemaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    Rcpp::traits::input_parameter< XPtr<tiledb::ArraySchema> >::type schema(schemaSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_create(uri, schema));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array
XPtr<tiledb::Array> libtiledb_array(XPtr<tiledb::Context> ctx, std::string uri, std::string type);
RcppExport SEXP _tiledb_libtiledb_array(SEXP ctxSEXP, SEXP uriSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Context> >::type ctx(ctxSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array(ctx, uri, type));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_is_open
bool libtiledb_array_is_open(XPtr<tiledb::Array> array);
RcppExport SEXP _tiledb_libtiledb_array_is_open(SEXP arraySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Array> >::type array(arraySEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_is_open(array));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_get_uri
std::string libtiledb_array_get_uri(XPtr<tiledb::Array> array);
RcppExport SEXP _tiledb_libtiledb_array_get_uri(SEXP arraySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Array> >::type array(arraySEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_get_uri(array));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_get_schema
XPtr<tiledb::ArraySchema> libtiledb_array_get_schema(XPtr<tiledb::Array> array);
RcppExport SEXP _tiledb_libtiledb_array_get_schema(SEXP arraySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Array> >::type array(arraySEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_get_schema(array));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_open
XPtr<tiledb::Array> libtiledb_array_open(XPtr<tiledb::Array> array, std::string query_type);
RcppExport SEXP _tiledb_libtiledb_array_open(SEXP arraySEXP, SEXP query_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Array> >::type array(arraySEXP);
    Rcpp::traits::input_parameter< std::string >::type query_type(query_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_open(array, query_type));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_reopen
XPtr<tiledb::Array> libtiledb_array_reopen(XPtr<tiledb::Array> array);
RcppExport SEXP _tiledb_libtiledb_array_reopen(SEXP arraySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Array> >::type array(arraySEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_reopen(array));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_close
XPtr<tiledb::Array> libtiledb_array_close(XPtr<tiledb::Array> array);
RcppExport SEXP _tiledb_libtiledb_array_close(SEXP arraySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Array> >::type array(arraySEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_close(array));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_query_type
std::string libtiledb_array_query_type(XPtr<tiledb::Array> array);
RcppExport SEXP _tiledb_libtiledb_array_query_type(SEXP arraySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Array> >::type array(arraySEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_query_type(array));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_nonempty_domain
List libtiledb_array_nonempty_domain(XPtr<tiledb::Array> array);
RcppExport SEXP _tiledb_libtiledb_array_nonempty_domain(SEXP arraySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Array> >::type array(arraySEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_nonempty_domain(array));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_array_consolidate
std::string libtiledb_array_consolidate(XPtr<tiledb::Context> ctx, std::string uri);
RcppExport SEXP _tiledb_libtiledb_array_consolidate(SEXP ctxSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Context> >::type ctx(ctxSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_array_consolidate(ctx, uri));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_query
XPtr<tiledb::Query> tiledb_query(XPtr<tiledb::Context> ctx, XPtr<tiledb::Array> array, std::string type);
RcppExport SEXP _tiledb_tiledb_query(SEXP ctxSEXP, SEXP arraySEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Context> >::type ctx(ctxSEXP);
    Rcpp::traits::input_parameter< XPtr<tiledb::Array> >::type array(arraySEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_query(ctx, array, type));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_query_set_layout
XPtr<tiledb::Query> tiledb_query_set_layout(XPtr<tiledb::Query> query, std::string layout);
RcppExport SEXP _tiledb_tiledb_query_set_layout(SEXP querySEXP, SEXP layoutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Query> >::type query(querySEXP);
    Rcpp::traits::input_parameter< std::string >::type layout(layoutSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_query_set_layout(query, layout));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_query_set_subarray
XPtr<tiledb::Query> tiledb_query_set_subarray(XPtr<tiledb::Query> query, SEXP subarray);
RcppExport SEXP _tiledb_tiledb_query_set_subarray(SEXP querySEXP, SEXP subarraySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Query> >::type query(querySEXP);
    Rcpp::traits::input_parameter< SEXP >::type subarray(subarraySEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_query_set_subarray(query, subarray));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_query_set_buffer
XPtr<tiledb::Query> tiledb_query_set_buffer(XPtr<tiledb::Query> query, std::string attr, SEXP buffer);
RcppExport SEXP _tiledb_tiledb_query_set_buffer(SEXP querySEXP, SEXP attrSEXP, SEXP bufferSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Query> >::type query(querySEXP);
    Rcpp::traits::input_parameter< std::string >::type attr(attrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type buffer(bufferSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_query_set_buffer(query, attr, buffer));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_query_submit
XPtr<tiledb::Query> tiledb_query_submit(XPtr<tiledb::Query> query);
RcppExport SEXP _tiledb_tiledb_query_submit(SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Query> >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_query_submit(query));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_query_finalize
XPtr<tiledb::Query> tiledb_query_finalize(XPtr<tiledb::Query> query);
RcppExport SEXP _tiledb_tiledb_query_finalize(SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Query> >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_query_finalize(query));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_query_status
std::string tiledb_query_status(XPtr<tiledb::Query> query);
RcppExport SEXP _tiledb_tiledb_query_status(SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Query> >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_query_status(query));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_group_create
std::string libtiledb_group_create(XPtr<tiledb::Context> ctx, std::string uri);
RcppExport SEXP _tiledb_libtiledb_group_create(SEXP ctxSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Context> >::type ctx(ctxSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_group_create(ctx, uri));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_object_type
std::string libtiledb_object_type(XPtr<tiledb::Context> ctx, std::string uri);
RcppExport SEXP _tiledb_libtiledb_object_type(SEXP ctxSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Context> >::type ctx(ctxSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_object_type(ctx, uri));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_object_remove
std::string libtiledb_object_remove(XPtr<tiledb::Context> ctx, std::string uri);
RcppExport SEXP _tiledb_libtiledb_object_remove(SEXP ctxSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Context> >::type ctx(ctxSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_object_remove(ctx, uri));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_object_move
std::string libtiledb_object_move(XPtr<tiledb::Context> ctx, std::string old_uri, std::string new_uri);
RcppExport SEXP _tiledb_libtiledb_object_move(SEXP ctxSEXP, SEXP old_uriSEXP, SEXP new_uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Context> >::type ctx(ctxSEXP);
    Rcpp::traits::input_parameter< std::string >::type old_uri(old_uriSEXP);
    Rcpp::traits::input_parameter< std::string >::type new_uri(new_uriSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_object_move(ctx, old_uri, new_uri));
    return rcpp_result_gen;
END_RCPP
}
// libtiledb_object_walk
DataFrame libtiledb_object_walk(XPtr<tiledb::Context> ctx, std::string uri, std::string order, bool recursive);
RcppExport SEXP _tiledb_libtiledb_object_walk(SEXP ctxSEXP, SEXP uriSEXP, SEXP orderSEXP, SEXP recursiveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Context> >::type ctx(ctxSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    Rcpp::traits::input_parameter< std::string >::type order(orderSEXP);
    Rcpp::traits::input_parameter< bool >::type recursive(recursiveSEXP);
    rcpp_result_gen = Rcpp::wrap(libtiledb_object_walk(ctx, uri, order, recursive));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_vfs
XPtr<tiledb::VFS> tiledb_vfs(XPtr<tiledb::Context> ctx, Nullable<XPtr<tiledb::Config>> config);
RcppExport SEXP _tiledb_tiledb_vfs(SEXP ctxSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::Context> >::type ctx(ctxSEXP);
    Rcpp::traits::input_parameter< Nullable<XPtr<tiledb::Config>> >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_vfs(ctx, config));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_vfs_create_bucket
std::string tiledb_vfs_create_bucket(XPtr<tiledb::VFS> vfs, std::string uri);
RcppExport SEXP _tiledb_tiledb_vfs_create_bucket(SEXP vfsSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::VFS> >::type vfs(vfsSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_vfs_create_bucket(vfs, uri));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_vfs_remove_bucket
std::string tiledb_vfs_remove_bucket(XPtr<tiledb::VFS> vfs, std::string uri);
RcppExport SEXP _tiledb_tiledb_vfs_remove_bucket(SEXP vfsSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::VFS> >::type vfs(vfsSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_vfs_remove_bucket(vfs, uri));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_vfs_is_bucket
bool tiledb_vfs_is_bucket(XPtr<tiledb::VFS> vfs, std::string uri);
RcppExport SEXP _tiledb_tiledb_vfs_is_bucket(SEXP vfsSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::VFS> >::type vfs(vfsSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_vfs_is_bucket(vfs, uri));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_vfs_is_empty_bucket
bool tiledb_vfs_is_empty_bucket(XPtr<tiledb::VFS> vfs, std::string uri);
RcppExport SEXP _tiledb_tiledb_vfs_is_empty_bucket(SEXP vfsSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::VFS> >::type vfs(vfsSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_vfs_is_empty_bucket(vfs, uri));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_vfs_empty_bucket
std::string tiledb_vfs_empty_bucket(XPtr<tiledb::VFS> vfs, std::string uri);
RcppExport SEXP _tiledb_tiledb_vfs_empty_bucket(SEXP vfsSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::VFS> >::type vfs(vfsSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_vfs_empty_bucket(vfs, uri));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_vfs_create_dir
std::string tiledb_vfs_create_dir(XPtr<tiledb::VFS> vfs, std::string uri);
RcppExport SEXP _tiledb_tiledb_vfs_create_dir(SEXP vfsSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::VFS> >::type vfs(vfsSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_vfs_create_dir(vfs, uri));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_vfs_is_dir
bool tiledb_vfs_is_dir(XPtr<tiledb::VFS> vfs, std::string uri);
RcppExport SEXP _tiledb_tiledb_vfs_is_dir(SEXP vfsSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::VFS> >::type vfs(vfsSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_vfs_is_dir(vfs, uri));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_vfs_remove_dir
std::string tiledb_vfs_remove_dir(XPtr<tiledb::VFS> vfs, std::string uri);
RcppExport SEXP _tiledb_tiledb_vfs_remove_dir(SEXP vfsSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::VFS> >::type vfs(vfsSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_vfs_remove_dir(vfs, uri));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_vfs_is_file
bool tiledb_vfs_is_file(XPtr<tiledb::VFS> vfs, std::string uri);
RcppExport SEXP _tiledb_tiledb_vfs_is_file(SEXP vfsSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::VFS> >::type vfs(vfsSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_vfs_is_file(vfs, uri));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_vfs_remove_file
std::string tiledb_vfs_remove_file(XPtr<tiledb::VFS> vfs, std::string uri);
RcppExport SEXP _tiledb_tiledb_vfs_remove_file(SEXP vfsSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::VFS> >::type vfs(vfsSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_vfs_remove_file(vfs, uri));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_vfs_file_size
R_xlen_t tiledb_vfs_file_size(XPtr<tiledb::VFS> vfs, std::string uri);
RcppExport SEXP _tiledb_tiledb_vfs_file_size(SEXP vfsSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::VFS> >::type vfs(vfsSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_vfs_file_size(vfs, uri));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_vfs_move_file
std::string tiledb_vfs_move_file(XPtr<tiledb::VFS> vfs, std::string old_uri, std::string new_uri);
RcppExport SEXP _tiledb_tiledb_vfs_move_file(SEXP vfsSEXP, SEXP old_uriSEXP, SEXP new_uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::VFS> >::type vfs(vfsSEXP);
    Rcpp::traits::input_parameter< std::string >::type old_uri(old_uriSEXP);
    Rcpp::traits::input_parameter< std::string >::type new_uri(new_uriSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_vfs_move_file(vfs, old_uri, new_uri));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_vfs_move_dir
std::string tiledb_vfs_move_dir(XPtr<tiledb::VFS> vfs, std::string old_uri, std::string new_uri);
RcppExport SEXP _tiledb_tiledb_vfs_move_dir(SEXP vfsSEXP, SEXP old_uriSEXP, SEXP new_uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::VFS> >::type vfs(vfsSEXP);
    Rcpp::traits::input_parameter< std::string >::type old_uri(old_uriSEXP);
    Rcpp::traits::input_parameter< std::string >::type new_uri(new_uriSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_vfs_move_dir(vfs, old_uri, new_uri));
    return rcpp_result_gen;
END_RCPP
}
// tiledb_vfs_touch
std::string tiledb_vfs_touch(XPtr<tiledb::VFS> vfs, std::string uri);
RcppExport SEXP _tiledb_tiledb_vfs_touch(SEXP vfsSEXP, SEXP uriSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<tiledb::VFS> >::type vfs(vfsSEXP);
    Rcpp::traits::input_parameter< std::string >::type uri(uriSEXP);
    rcpp_result_gen = Rcpp::wrap(tiledb_vfs_touch(vfs, uri));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tiledb_tiledb_datatype_R_type", (DL_FUNC) &_tiledb_tiledb_datatype_R_type, 1},
    {"_tiledb_libtiledb_version", (DL_FUNC) &_tiledb_libtiledb_version, 0},
    {"_tiledb_libtiledb_ctx", (DL_FUNC) &_tiledb_libtiledb_ctx, 1},
    {"_tiledb_libtiledb_config_save_to_file", (DL_FUNC) &_tiledb_libtiledb_config_save_to_file, 2},
    {"_tiledb_libtiledb_config_load_from_file", (DL_FUNC) &_tiledb_libtiledb_config_load_from_file, 1},
    {"_tiledb_libtiledb_ctx_config", (DL_FUNC) &_tiledb_libtiledb_ctx_config, 1},
    {"_tiledb_libtiledb_ctx_is_supported_fs", (DL_FUNC) &_tiledb_libtiledb_ctx_is_supported_fs, 2},
    {"_tiledb_libtiledb_config", (DL_FUNC) &_tiledb_libtiledb_config, 1},
    {"_tiledb_libtiledb_config_vector", (DL_FUNC) &_tiledb_libtiledb_config_vector, 1},
    {"_tiledb_libtiledb_config_set", (DL_FUNC) &_tiledb_libtiledb_config_set, 3},
    {"_tiledb_libtiledb_config_get", (DL_FUNC) &_tiledb_libtiledb_config_get, 2},
    {"_tiledb_libtiledb_config_dump", (DL_FUNC) &_tiledb_libtiledb_config_dump, 1},
    {"_tiledb_libtiledb_dim", (DL_FUNC) &_tiledb_libtiledb_dim, 5},
    {"_tiledb_libtiledb_dim_name", (DL_FUNC) &_tiledb_libtiledb_dim_name, 1},
    {"_tiledb_libtiledb_dim_domain", (DL_FUNC) &_tiledb_libtiledb_dim_domain, 1},
    {"_tiledb_libtiledb_dim_tile_extent", (DL_FUNC) &_tiledb_libtiledb_dim_tile_extent, 1},
    {"_tiledb_libtiledb_dim_datatype", (DL_FUNC) &_tiledb_libtiledb_dim_datatype, 1},
    {"_tiledb_dim_domain_subarray", (DL_FUNC) &_tiledb_dim_domain_subarray, 2},
    {"_tiledb_libtiledb_domain", (DL_FUNC) &_tiledb_libtiledb_domain, 2},
    {"_tiledb_libtiledb_domain_ndim", (DL_FUNC) &_tiledb_libtiledb_domain_ndim, 1},
    {"_tiledb_libtiledb_domain_dimensions", (DL_FUNC) &_tiledb_libtiledb_domain_dimensions, 1},
    {"_tiledb_libtiledb_domain_datatype", (DL_FUNC) &_tiledb_libtiledb_domain_datatype, 1},
    {"_tiledb_libtiledb_domain_dump", (DL_FUNC) &_tiledb_libtiledb_domain_dump, 1},
    {"_tiledb_libtiledb_compressor", (DL_FUNC) &_tiledb_libtiledb_compressor, 2},
    {"_tiledb_libtiledb_compressor_type", (DL_FUNC) &_tiledb_libtiledb_compressor_type, 1},
    {"_tiledb_libtiledb_compressor_level", (DL_FUNC) &_tiledb_libtiledb_compressor_level, 1},
    {"_tiledb_libtiledb_attr", (DL_FUNC) &_tiledb_libtiledb_attr, 5},
    {"_tiledb_libtiledb_attr_name", (DL_FUNC) &_tiledb_libtiledb_attr_name, 1},
    {"_tiledb_libtiledb_attr_datatype", (DL_FUNC) &_tiledb_libtiledb_attr_datatype, 1},
    {"_tiledb_libtiledb_attr_compressor", (DL_FUNC) &_tiledb_libtiledb_attr_compressor, 1},
    {"_tiledb_libtiledb_attr_ncells", (DL_FUNC) &_tiledb_libtiledb_attr_ncells, 1},
    {"_tiledb_libtiledb_attr_dump", (DL_FUNC) &_tiledb_libtiledb_attr_dump, 1},
    {"_tiledb_libtiledb_array_schema", (DL_FUNC) &_tiledb_libtiledb_array_schema, 8},
    {"_tiledb_libtiledb_array_schema_domain", (DL_FUNC) &_tiledb_libtiledb_array_schema_domain, 1},
    {"_tiledb_libtiledb_array_schema_attributes", (DL_FUNC) &_tiledb_libtiledb_array_schema_attributes, 1},
    {"_tiledb_libtiledb_array_schema_cell_order", (DL_FUNC) &_tiledb_libtiledb_array_schema_cell_order, 1},
    {"_tiledb_libtiledb_array_schema_tile_order", (DL_FUNC) &_tiledb_libtiledb_array_schema_tile_order, 1},
    {"_tiledb_libtiledb_array_schema_coords_compressor", (DL_FUNC) &_tiledb_libtiledb_array_schema_coords_compressor, 1},
    {"_tiledb_libtiledb_array_schema_offsets_compressor", (DL_FUNC) &_tiledb_libtiledb_array_schema_offsets_compressor, 1},
    {"_tiledb_libtiledb_array_schema_sparse", (DL_FUNC) &_tiledb_libtiledb_array_schema_sparse, 1},
    {"_tiledb_libtiledb_array_schema_load", (DL_FUNC) &_tiledb_libtiledb_array_schema_load, 2},
    {"_tiledb_libtiledb_array_schema_dump", (DL_FUNC) &_tiledb_libtiledb_array_schema_dump, 1},
    {"_tiledb_libtiledb_array_create", (DL_FUNC) &_tiledb_libtiledb_array_create, 2},
    {"_tiledb_libtiledb_array", (DL_FUNC) &_tiledb_libtiledb_array, 3},
    {"_tiledb_libtiledb_array_is_open", (DL_FUNC) &_tiledb_libtiledb_array_is_open, 1},
    {"_tiledb_libtiledb_array_get_uri", (DL_FUNC) &_tiledb_libtiledb_array_get_uri, 1},
    {"_tiledb_libtiledb_array_get_schema", (DL_FUNC) &_tiledb_libtiledb_array_get_schema, 1},
    {"_tiledb_libtiledb_array_open", (DL_FUNC) &_tiledb_libtiledb_array_open, 2},
    {"_tiledb_libtiledb_array_reopen", (DL_FUNC) &_tiledb_libtiledb_array_reopen, 1},
    {"_tiledb_libtiledb_array_close", (DL_FUNC) &_tiledb_libtiledb_array_close, 1},
    {"_tiledb_libtiledb_array_query_type", (DL_FUNC) &_tiledb_libtiledb_array_query_type, 1},
    {"_tiledb_libtiledb_array_nonempty_domain", (DL_FUNC) &_tiledb_libtiledb_array_nonempty_domain, 1},
    {"_tiledb_libtiledb_array_consolidate", (DL_FUNC) &_tiledb_libtiledb_array_consolidate, 2},
    {"_tiledb_tiledb_query", (DL_FUNC) &_tiledb_tiledb_query, 3},
    {"_tiledb_tiledb_query_set_layout", (DL_FUNC) &_tiledb_tiledb_query_set_layout, 2},
    {"_tiledb_tiledb_query_set_subarray", (DL_FUNC) &_tiledb_tiledb_query_set_subarray, 2},
    {"_tiledb_tiledb_query_set_buffer", (DL_FUNC) &_tiledb_tiledb_query_set_buffer, 3},
    {"_tiledb_tiledb_query_submit", (DL_FUNC) &_tiledb_tiledb_query_submit, 1},
    {"_tiledb_tiledb_query_finalize", (DL_FUNC) &_tiledb_tiledb_query_finalize, 1},
    {"_tiledb_tiledb_query_status", (DL_FUNC) &_tiledb_tiledb_query_status, 1},
    {"_tiledb_libtiledb_group_create", (DL_FUNC) &_tiledb_libtiledb_group_create, 2},
    {"_tiledb_libtiledb_object_type", (DL_FUNC) &_tiledb_libtiledb_object_type, 2},
    {"_tiledb_libtiledb_object_remove", (DL_FUNC) &_tiledb_libtiledb_object_remove, 2},
    {"_tiledb_libtiledb_object_move", (DL_FUNC) &_tiledb_libtiledb_object_move, 3},
    {"_tiledb_libtiledb_object_walk", (DL_FUNC) &_tiledb_libtiledb_object_walk, 4},
    {"_tiledb_tiledb_vfs", (DL_FUNC) &_tiledb_tiledb_vfs, 2},
    {"_tiledb_tiledb_vfs_create_bucket", (DL_FUNC) &_tiledb_tiledb_vfs_create_bucket, 2},
    {"_tiledb_tiledb_vfs_remove_bucket", (DL_FUNC) &_tiledb_tiledb_vfs_remove_bucket, 2},
    {"_tiledb_tiledb_vfs_is_bucket", (DL_FUNC) &_tiledb_tiledb_vfs_is_bucket, 2},
    {"_tiledb_tiledb_vfs_is_empty_bucket", (DL_FUNC) &_tiledb_tiledb_vfs_is_empty_bucket, 2},
    {"_tiledb_tiledb_vfs_empty_bucket", (DL_FUNC) &_tiledb_tiledb_vfs_empty_bucket, 2},
    {"_tiledb_tiledb_vfs_create_dir", (DL_FUNC) &_tiledb_tiledb_vfs_create_dir, 2},
    {"_tiledb_tiledb_vfs_is_dir", (DL_FUNC) &_tiledb_tiledb_vfs_is_dir, 2},
    {"_tiledb_tiledb_vfs_remove_dir", (DL_FUNC) &_tiledb_tiledb_vfs_remove_dir, 2},
    {"_tiledb_tiledb_vfs_is_file", (DL_FUNC) &_tiledb_tiledb_vfs_is_file, 2},
    {"_tiledb_tiledb_vfs_remove_file", (DL_FUNC) &_tiledb_tiledb_vfs_remove_file, 2},
    {"_tiledb_tiledb_vfs_file_size", (DL_FUNC) &_tiledb_tiledb_vfs_file_size, 2},
    {"_tiledb_tiledb_vfs_move_file", (DL_FUNC) &_tiledb_tiledb_vfs_move_file, 3},
    {"_tiledb_tiledb_vfs_move_dir", (DL_FUNC) &_tiledb_tiledb_vfs_move_dir, 3},
    {"_tiledb_tiledb_vfs_touch", (DL_FUNC) &_tiledb_tiledb_vfs_touch, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_tiledb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
