# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tiledb_version <- function() {
    .Call(`_tiledb_tiledb_version`)
}

tiledb_ctx <- function() {
    .Call(`_tiledb_tiledb_ctx`)
}

tiledb_config <- function() {
    .Call(`_tiledb_tiledb_config`)
}

tiledb_config_dump <- function(config) {
    invisible(.Call(`_tiledb_tiledb_config_dump`, config))
}

