# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

libtiledb_query_set_coordinates <- function(query, coords, dtype) {
    .Call(`_tiledb_libtiledb_query_set_coordinates`, query, coords, dtype)
}

libtiledb_query_buffer_var_char_alloc <- function(array, subarray, attribute, szoffsets = 0L, szdata = 0L) {
    .Call(`_tiledb_libtiledb_query_buffer_var_char_alloc`, array, subarray, attribute, szoffsets, szdata)
}

libtiledb_query_buffer_var_vec_alloc <- function(array, subarray, attribute, szoffsets = 0L, szdata = 0L) {
    .Call(`_tiledb_libtiledb_query_buffer_var_vec_alloc`, array, subarray, attribute, szoffsets, szdata)
}

libtiledb_coords <- function() {
    .Call(`_tiledb_libtiledb_coords`)
}

libtiledb_array_max_buffer_elements_with_type <- function(array, subarray, attribute, typestr) {
    .Call(`_tiledb_libtiledb_array_max_buffer_elements_with_type`, array, subarray, attribute, typestr)
}

libtiledb_array_max_buffer_elements <- function(array, subarray, attribute) {
    .Call(`_tiledb_libtiledb_array_max_buffer_elements`, array, subarray, attribute)
}

libtiledb_array_max_buffer_elements_vec <- function(array, subarray, attribute) {
    .Call(`_tiledb_libtiledb_array_max_buffer_elements_vec`, array, subarray, attribute)
}

tiledb_datatype_R_type <- function(datatype) {
    .Call(`_tiledb_tiledb_datatype_R_type`, datatype)
}

libtiledb_version <- function() {
    .Call(`_tiledb_libtiledb_version`)
}

libtiledb_ctx <- function(config = NULL) {
    .Call(`_tiledb_libtiledb_ctx`, config)
}

libtiledb_ctx_config <- function(ctx) {
    .Call(`_tiledb_libtiledb_ctx_config`, ctx)
}

libtiledb_ctx_is_supported_fs <- function(ctx, scheme) {
    .Call(`_tiledb_libtiledb_ctx_is_supported_fs`, ctx, scheme)
}

libtiledb_ctx_set_tag <- function(ctx, key, value) {
    invisible(.Call(`_tiledb_libtiledb_ctx_set_tag`, ctx, key, value))
}

libtiledb_config <- function(config = NULL) {
    .Call(`_tiledb_libtiledb_config`, config)
}

libtiledb_config_save_to_file <- function(config, filename) {
    .Call(`_tiledb_libtiledb_config_save_to_file`, config, filename)
}

libtiledb_config_load_from_file <- function(filename) {
    .Call(`_tiledb_libtiledb_config_load_from_file`, filename)
}

libtiledb_config_vector <- function(config) {
    .Call(`_tiledb_libtiledb_config_vector`, config)
}

libtiledb_config_set <- function(config, param, value) {
    .Call(`_tiledb_libtiledb_config_set`, config, param, value)
}

libtiledb_config_get <- function(config, params) {
    .Call(`_tiledb_libtiledb_config_get`, config, params)
}

libtiledb_config_unset <- function(config, param) {
    .Call(`_tiledb_libtiledb_config_unset`, config, param)
}

libtiledb_config_dump <- function(config) {
    invisible(.Call(`_tiledb_libtiledb_config_dump`, config))
}

libtiledb_dim <- function(ctx, name, type, domain, tile_extent) {
    .Call(`_tiledb_libtiledb_dim`, ctx, name, type, domain, tile_extent)
}

libtiledb_dim_get_name <- function(dim) {
    .Call(`_tiledb_libtiledb_dim_get_name`, dim)
}

libtiledb_dim_get_domain <- function(dim) {
    .Call(`_tiledb_libtiledb_dim_get_domain`, dim)
}

libtiledb_dim_get_tile_extent <- function(dim) {
    .Call(`_tiledb_libtiledb_dim_get_tile_extent`, dim)
}

libtiledb_dim_get_datatype <- function(dim) {
    .Call(`_tiledb_libtiledb_dim_get_datatype`, dim)
}

dim_domain_subarray <- function(domain, subscript) {
    .Call(`_tiledb_dim_domain_subarray`, domain, subscript)
}

libtiledb_dim_get_cell_val_num <- function(dim) {
    .Call(`_tiledb_libtiledb_dim_get_cell_val_num`, dim)
}

libtiledb_domain <- function(ctx, dims) {
    .Call(`_tiledb_libtiledb_domain`, ctx, dims)
}

libtiledb_domain_get_type <- function(domain) {
    .Call(`_tiledb_libtiledb_domain_get_type`, domain)
}

libtiledb_domain_get_ndim <- function(domain) {
    .Call(`_tiledb_libtiledb_domain_get_ndim`, domain)
}

libtiledb_domain_get_dimensions <- function(domain) {
    .Call(`_tiledb_libtiledb_domain_get_dimensions`, domain)
}

libtiledb_domain_dump <- function(domain) {
    invisible(.Call(`_tiledb_libtiledb_domain_dump`, domain))
}

libtiledb_filter <- function(ctx, filter) {
    .Call(`_tiledb_libtiledb_filter`, ctx, filter)
}

libtiledb_filter_get_type <- function(filter) {
    .Call(`_tiledb_libtiledb_filter_get_type`, filter)
}

libtiledb_filter_get_option <- function(filter, filter_option_str) {
    .Call(`_tiledb_libtiledb_filter_get_option`, filter, filter_option_str)
}

libtiledb_filter_set_option <- function(filter, filter_option_str, value) {
    invisible(.Call(`_tiledb_libtiledb_filter_set_option`, filter, filter_option_str, value))
}

libtiledb_filter_list <- function(ctx, filters) {
    .Call(`_tiledb_libtiledb_filter_list`, ctx, filters)
}

libtiledb_filter_list_set_max_chunk_size <- function(filterList, max_chunk_sie) {
    invisible(.Call(`_tiledb_libtiledb_filter_list_set_max_chunk_size`, filterList, max_chunk_sie))
}

libtiledb_filter_list_get_max_chunk_size <- function(filterList) {
    .Call(`_tiledb_libtiledb_filter_list_get_max_chunk_size`, filterList)
}

libtiledb_filter_list_get_nfilters <- function(filterList) {
    .Call(`_tiledb_libtiledb_filter_list_get_nfilters`, filterList)
}

libtiledb_filter_list_get_filter_from_index <- function(filterList, filter_index) {
    .Call(`_tiledb_libtiledb_filter_list_get_filter_from_index`, filterList, filter_index)
}

libtiledb_attribute <- function(ctx, name, type, filter_list, ncells) {
    .Call(`_tiledb_libtiledb_attribute`, ctx, name, type, filter_list, ncells)
}

libtiledb_attribute_get_name <- function(attr) {
    .Call(`_tiledb_libtiledb_attribute_get_name`, attr)
}

libtiledb_attribute_get_type <- function(attr) {
    .Call(`_tiledb_libtiledb_attribute_get_type`, attr)
}

libtiledb_attribute_get_cell_size <- function(attr) {
    .Call(`_tiledb_libtiledb_attribute_get_cell_size`, attr)
}

libtiledb_attribute_get_filter_list <- function(attr) {
    .Call(`_tiledb_libtiledb_attribute_get_filter_list`, attr)
}

libtiledb_attribute_get_cell_val_num <- function(attr) {
    .Call(`_tiledb_libtiledb_attribute_get_cell_val_num`, attr)
}

libtiledb_attribute_set_cell_val_num <- function(attr, num) {
    invisible(.Call(`_tiledb_libtiledb_attribute_set_cell_val_num`, attr, num))
}

libtiledb_attribute_is_variable_sized <- function(attr) {
    .Call(`_tiledb_libtiledb_attribute_is_variable_sized`, attr)
}

libtiledb_attribute_dump <- function(attr) {
    invisible(.Call(`_tiledb_libtiledb_attribute_dump`, attr))
}

libtiledb_attribute_set_fill_value <- function(attr, val) {
    invisible(.Call(`_tiledb_libtiledb_attribute_set_fill_value`, attr, val))
}

libtiledb_attribute_get_fill_value <- function(attr) {
    .Call(`_tiledb_libtiledb_attribute_get_fill_value`, attr)
}

libtiledb_array_schema <- function(ctx, domain, attributes, cell_order, tile_order, coords_filter_list = NULL, offsets_filter_list = NULL, sparse = FALSE) {
    .Call(`_tiledb_libtiledb_array_schema`, ctx, domain, attributes, cell_order, tile_order, coords_filter_list, offsets_filter_list, sparse)
}

libtiledb_array_schema_create <- function(ctx, atstr) {
    .Call(`_tiledb_libtiledb_array_schema_create`, ctx, atstr)
}

libtiledb_array_schema_load <- function(ctx, uri) {
    .Call(`_tiledb_libtiledb_array_schema_load`, ctx, uri)
}

libtiledb_array_schema_load_with_key <- function(ctx, uri, key) {
    .Call(`_tiledb_libtiledb_array_schema_load_with_key`, ctx, uri, key)
}

libtiledb_array_schema_set_domain <- function(schema, dom) {
    invisible(.Call(`_tiledb_libtiledb_array_schema_set_domain`, schema, dom))
}

libtiledb_array_schema_get_domain <- function(schema) {
    .Call(`_tiledb_libtiledb_array_schema_get_domain`, schema)
}

libtiledb_array_schema_add_attribute <- function(schema, attr) {
    invisible(.Call(`_tiledb_libtiledb_array_schema_add_attribute`, schema, attr))
}

libtiledb_array_schema_attributes <- function(schema) {
    .Call(`_tiledb_libtiledb_array_schema_attributes`, schema)
}

libtiledb_array_schema_get_array_type <- function(schema) {
    .Call(`_tiledb_libtiledb_array_schema_get_array_type`, schema)
}

libtiledb_array_schema_set_cell_order <- function(schema, ord) {
    invisible(.Call(`_tiledb_libtiledb_array_schema_set_cell_order`, schema, ord))
}

libtiledb_array_schema_get_cell_order <- function(schema) {
    .Call(`_tiledb_libtiledb_array_schema_get_cell_order`, schema)
}

libtiledb_array_schema_set_tile_order <- function(schema, ord) {
    invisible(.Call(`_tiledb_libtiledb_array_schema_set_tile_order`, schema, ord))
}

libtiledb_array_schema_get_tile_order <- function(schema) {
    .Call(`_tiledb_libtiledb_array_schema_get_tile_order`, schema)
}

libtiledb_array_schema_set_capacity <- function(schema, cap) {
    invisible(.Call(`_tiledb_libtiledb_array_schema_set_capacity`, schema, cap))
}

libtiledb_array_schema_get_capacity <- function(schema) {
    .Call(`_tiledb_libtiledb_array_schema_get_capacity`, schema)
}

libtiledb_array_schema_get_allows_dups <- function(schema) {
    .Call(`_tiledb_libtiledb_array_schema_get_allows_dups`, schema)
}

libtiledb_array_schema_set_allows_dups <- function(schema, allows_dups) {
    .Call(`_tiledb_libtiledb_array_schema_set_allows_dups`, schema, allows_dups)
}

libtiledb_array_schema_get_coords_filter_list <- function(schema) {
    .Call(`_tiledb_libtiledb_array_schema_get_coords_filter_list`, schema)
}

libtiledb_array_schema_offsets_filter_list <- function(schema) {
    .Call(`_tiledb_libtiledb_array_schema_offsets_filter_list`, schema)
}

libtiledb_array_schema_get_attribute_num <- function(schema) {
    .Call(`_tiledb_libtiledb_array_schema_get_attribute_num`, schema)
}

libtiledb_array_schema_get_attribute_from_index <- function(schema, ind) {
    .Call(`_tiledb_libtiledb_array_schema_get_attribute_from_index`, schema, ind)
}

libtiledb_array_schema_get_attribute_from_name <- function(schema, name) {
    .Call(`_tiledb_libtiledb_array_schema_get_attribute_from_name`, schema, name)
}

libtiledb_array_schema_has_attribute <- function(schema, name) {
    .Call(`_tiledb_libtiledb_array_schema_has_attribute`, schema, name)
}

libtiledb_array_schema_sparse <- function(schema) {
    .Call(`_tiledb_libtiledb_array_schema_sparse`, schema)
}

libtiledb_array_schema_dump <- function(schema) {
    invisible(.Call(`_tiledb_libtiledb_array_schema_dump`, schema))
}

libtiledb_array_schema_check <- function(schema) {
    invisible(.Call(`_tiledb_libtiledb_array_schema_check`, schema))
}

libtiledb_array_create <- function(uri, schema) {
    .Call(`_tiledb_libtiledb_array_create`, uri, schema)
}

libtiledb_array_create_with_key <- function(uri, schema, encryption_key) {
    .Call(`_tiledb_libtiledb_array_create_with_key`, uri, schema, encryption_key)
}

libtiledb_array_open <- function(ctx, uri, type) {
    .Call(`_tiledb_libtiledb_array_open`, ctx, uri, type)
}

libtiledb_array_open_at <- function(ctx, uri, type, tstamp) {
    .Call(`_tiledb_libtiledb_array_open_at`, ctx, uri, type, tstamp)
}

libtiledb_array_open_with_key <- function(ctx, uri, type, enc_key) {
    .Call(`_tiledb_libtiledb_array_open_with_key`, ctx, uri, type, enc_key)
}

libtiledb_array_open_at_with_key <- function(ctx, uri, type, enc_key, tstamp) {
    .Call(`_tiledb_libtiledb_array_open_at_with_key`, ctx, uri, type, enc_key, tstamp)
}

libtiledb_array_open_with_ptr <- function(array, query_type) {
    .Call(`_tiledb_libtiledb_array_open_with_ptr`, array, query_type)
}

libtiledb_array_is_open <- function(array) {
    .Call(`_tiledb_libtiledb_array_is_open`, array)
}

libtiledb_array_is_open_for_reading <- function(array) {
    .Call(`_tiledb_libtiledb_array_is_open_for_reading`, array)
}

libtiledb_array_is_open_for_writing <- function(array) {
    .Call(`_tiledb_libtiledb_array_is_open_for_writing`, array)
}

libtiledb_array_get_uri <- function(array) {
    .Call(`_tiledb_libtiledb_array_get_uri`, array)
}

libtiledb_array_get_schema <- function(array) {
    .Call(`_tiledb_libtiledb_array_get_schema`, array)
}

libtiledb_array_reopen <- function(array) {
    .Call(`_tiledb_libtiledb_array_reopen`, array)
}

libtiledb_array_close <- function(array) {
    .Call(`_tiledb_libtiledb_array_close`, array)
}

libtiledb_array_query_type <- function(array) {
    .Call(`_tiledb_libtiledb_array_query_type`, array)
}

libtiledb_array_get_non_empty_domain <- function(array) {
    .Call(`_tiledb_libtiledb_array_get_non_empty_domain`, array)
}

libtiledb_array_get_non_empty_domain_var_from_name <- function(array, name) {
    .Call(`_tiledb_libtiledb_array_get_non_empty_domain_var_from_name`, array, name)
}

libtiledb_array_get_non_empty_domain_var_from_index <- function(array, idx, typestr) {
    .Call(`_tiledb_libtiledb_array_get_non_empty_domain_var_from_index`, array, idx, typestr)
}

libtiledb_array_get_non_empty_domain_from_name <- function(array, name, typestr) {
    .Call(`_tiledb_libtiledb_array_get_non_empty_domain_from_name`, array, name, typestr)
}

libtiledb_array_non_empty_domain_from_index <- function(array, idx, typestr) {
    .Call(`_tiledb_libtiledb_array_non_empty_domain_from_index`, array, idx, typestr)
}

libtiledb_array_consolidate <- function(ctx, uri, cfgptr = NULL) {
    invisible(.Call(`_tiledb_libtiledb_array_consolidate`, ctx, uri, cfgptr))
}

libtiledb_array_put_metadata <- function(array, key, obj) {
    .Call(`_tiledb_libtiledb_array_put_metadata`, array, key, obj)
}

libtiledb_array_get_metadata_num <- function(array) {
    .Call(`_tiledb_libtiledb_array_get_metadata_num`, array)
}

libtiledb_array_get_metadata_from_index <- function(array, idx) {
    .Call(`_tiledb_libtiledb_array_get_metadata_from_index`, array, idx)
}

libtiledb_array_get_metadata_list <- function(array) {
    .Call(`_tiledb_libtiledb_array_get_metadata_list`, array)
}

libtiledb_array_delete_metadata <- function(array, key) {
    invisible(.Call(`_tiledb_libtiledb_array_delete_metadata`, array, key))
}

libtiledb_query <- function(ctx, array, type) {
    .Call(`_tiledb_libtiledb_query`, ctx, array, type)
}

libtiledb_query_type <- function(query) {
    .Call(`_tiledb_libtiledb_query_type`, query)
}

libtiledb_query_set_layout <- function(query, layout) {
    .Call(`_tiledb_libtiledb_query_set_layout`, query, layout)
}

libtiledb_query_layout <- function(query) {
    .Call(`_tiledb_libtiledb_query_layout`, query)
}

libtiledb_query_set_subarray_with_type <- function(query, subarray, typestr) {
    .Call(`_tiledb_libtiledb_query_set_subarray_with_type`, query, subarray, typestr)
}

libtiledb_query_set_subarray <- function(query, subarray) {
    .Call(`_tiledb_libtiledb_query_set_subarray`, query, subarray)
}

libtiledb_query_set_buffer <- function(query, attr, buffer) {
    .Call(`_tiledb_libtiledb_query_set_buffer`, query, attr, buffer)
}

libtiledb_query_buffer_var_char_alloc_direct <- function(szoffsets, szdata) {
    .Call(`_tiledb_libtiledb_query_buffer_var_char_alloc_direct`, szoffsets, szdata)
}

convertStringVectorIntoOffsetsAndString <- function(vec, offsets) {
    .Call(`_tiledb_convertStringVectorIntoOffsetsAndString`, vec, offsets)
}

libtiledb_query_buffer_var_char_create <- function(intoffsets, data) {
    .Call(`_tiledb_libtiledb_query_buffer_var_char_create`, intoffsets, data)
}

libtiledb_query_set_buffer_var_char <- function(query, attr, bufptr) {
    .Call(`_tiledb_libtiledb_query_set_buffer_var_char`, query, attr, bufptr)
}

libtiledb_query_get_buffer_var_char <- function(bufptr, len = 0L, nchar = 0L) {
    .Call(`_tiledb_libtiledb_query_get_buffer_var_char`, bufptr, len, nchar)
}

libtiledb_query_get_buffer_var_char_simple <- function(bufptr) {
    .Call(`_tiledb_libtiledb_query_get_buffer_var_char_simple`, bufptr)
}

libtiledb_query_buffer_var_vec_create <- function(intoffsets, data) {
    .Call(`_tiledb_libtiledb_query_buffer_var_vec_create`, intoffsets, data)
}

libtiledb_query_set_buffer_var_vec <- function(query, attr, buf) {
    .Call(`_tiledb_libtiledb_query_set_buffer_var_vec`, query, attr, buf)
}

libtiledb_query_get_buffer_var_vec <- function(query, attr, buf) {
    .Call(`_tiledb_libtiledb_query_get_buffer_var_vec`, query, attr, buf)
}

libtiledb_query_buffer_alloc_ptr <- function(array, domaintype, ncells) {
    .Call(`_tiledb_libtiledb_query_buffer_alloc_ptr`, array, domaintype, ncells)
}

libtiledb_query_buffer_assign_ptr <- function(buf, dtype, vec) {
    .Call(`_tiledb_libtiledb_query_buffer_assign_ptr`, buf, dtype, vec)
}

libtiledb_query_set_buffer_ptr <- function(query, attr, buf) {
    .Call(`_tiledb_libtiledb_query_set_buffer_ptr`, query, attr, buf)
}

libtiledb_query_get_buffer_ptr <- function(buf) {
    .Call(`_tiledb_libtiledb_query_get_buffer_ptr`, buf)
}

libtiledb_query_submit <- function(query) {
    .Call(`_tiledb_libtiledb_query_submit`, query)
}

libtiledb_query_finalize <- function(query) {
    .Call(`_tiledb_libtiledb_query_finalize`, query)
}

libtiledb_query_status <- function(query) {
    .Call(`_tiledb_libtiledb_query_status`, query)
}

libtiledb_query_result_buffer_elements <- function(query, attribute) {
    .Call(`_tiledb_libtiledb_query_result_buffer_elements`, query, attribute)
}

libtiledb_query_get_fragment_num <- function(query) {
    .Call(`_tiledb_libtiledb_query_get_fragment_num`, query)
}

libtiledb_query_get_fragment_uri <- function(query, idx) {
    .Call(`_tiledb_libtiledb_query_get_fragment_uri`, query, idx)
}

libtiledb_query_add_range <- function(query, iidx, starts, ends, strides = NULL) {
    .Call(`_tiledb_libtiledb_query_add_range`, query, iidx, starts, ends, strides)
}

libtiledb_query_add_range_with_type <- function(query, iidx, typestr, starts, ends, strides = NULL) {
    .Call(`_tiledb_libtiledb_query_add_range_with_type`, query, iidx, typestr, starts, ends, strides)
}

libtiledb_query_get_est_result_size <- function(query, attr) {
    .Call(`_tiledb_libtiledb_query_get_est_result_size`, query, attr)
}

libtiledb_query_get_est_result_size_var <- function(query, attr) {
    .Call(`_tiledb_libtiledb_query_get_est_result_size_var`, query, attr)
}

libtiledb_zip_coords_numeric <- function(coords, coord_length) {
    .Call(`_tiledb_libtiledb_zip_coords_numeric`, coords, coord_length)
}

libtiledb_zip_coords_integer <- function(coords, coord_length) {
    .Call(`_tiledb_libtiledb_zip_coords_integer`, coords, coord_length)
}

libtiledb_group_create <- function(ctx, uri) {
    .Call(`_tiledb_libtiledb_group_create`, ctx, uri)
}

libtiledb_object_type <- function(ctx, uri) {
    .Call(`_tiledb_libtiledb_object_type`, ctx, uri)
}

libtiledb_object_remove <- function(ctx, uri) {
    .Call(`_tiledb_libtiledb_object_remove`, ctx, uri)
}

libtiledb_object_move <- function(ctx, old_uri, new_uri) {
    .Call(`_tiledb_libtiledb_object_move`, ctx, old_uri, new_uri)
}

libtiledb_object_walk <- function(ctx, uri, order, recursive = FALSE) {
    .Call(`_tiledb_libtiledb_object_walk`, ctx, uri, order, recursive)
}

libtiledb_vfs <- function(ctx, config = NULL) {
    .Call(`_tiledb_libtiledb_vfs`, ctx, config)
}

libtiledb_vfs_create_bucket <- function(vfs, uri) {
    .Call(`_tiledb_libtiledb_vfs_create_bucket`, vfs, uri)
}

libtiledb_vfs_remove_bucket <- function(vfs, uri) {
    .Call(`_tiledb_libtiledb_vfs_remove_bucket`, vfs, uri)
}

libtiledb_vfs_is_bucket <- function(vfs, uri) {
    .Call(`_tiledb_libtiledb_vfs_is_bucket`, vfs, uri)
}

libtiledb_vfs_is_empty_bucket <- function(vfs, uri) {
    .Call(`_tiledb_libtiledb_vfs_is_empty_bucket`, vfs, uri)
}

libtiledb_vfs_empty_bucket <- function(vfs, uri) {
    .Call(`_tiledb_libtiledb_vfs_empty_bucket`, vfs, uri)
}

libtiledb_vfs_create_dir <- function(vfs, uri) {
    .Call(`_tiledb_libtiledb_vfs_create_dir`, vfs, uri)
}

libtiledb_vfs_is_dir <- function(vfs, uri) {
    .Call(`_tiledb_libtiledb_vfs_is_dir`, vfs, uri)
}

libtiledb_vfs_remove_dir <- function(vfs, uri) {
    .Call(`_tiledb_libtiledb_vfs_remove_dir`, vfs, uri)
}

libtiledb_vfs_is_file <- function(vfs, uri) {
    .Call(`_tiledb_libtiledb_vfs_is_file`, vfs, uri)
}

libtiledb_vfs_remove_file <- function(vfs, uri) {
    .Call(`_tiledb_libtiledb_vfs_remove_file`, vfs, uri)
}

libtiledb_vfs_file_size <- function(vfs, uri) {
    .Call(`_tiledb_libtiledb_vfs_file_size`, vfs, uri)
}

libtiledb_vfs_move_file <- function(vfs, old_uri, new_uri) {
    .Call(`_tiledb_libtiledb_vfs_move_file`, vfs, old_uri, new_uri)
}

libtiledb_vfs_move_dir <- function(vfs, old_uri, new_uri) {
    .Call(`_tiledb_libtiledb_vfs_move_dir`, vfs, old_uri, new_uri)
}

libtiledb_vfs_touch <- function(vfs, uri) {
    .Call(`_tiledb_libtiledb_vfs_touch`, vfs, uri)
}

libtiledb_stats_enable <- function() {
    invisible(.Call(`_tiledb_libtiledb_stats_enable`))
}

libtiledb_stats_disable <- function() {
    invisible(.Call(`_tiledb_libtiledb_stats_disable`))
}

libtiledb_stats_reset <- function() {
    invisible(.Call(`_tiledb_libtiledb_stats_reset`))
}

libtiledb_stats_dump <- function(path = "") {
    invisible(.Call(`_tiledb_libtiledb_stats_dump`, path))
}

