# Run CI for R based on copy of https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
  pull_request:

env:
  _R_CHECK_FORCE_SUGGESTS_: "FALSE"

jobs:
  ci:
    strategy:
      matrix:
        include:
          - {os: macOS-latest}
          - {os: ubuntu-22.04}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Bootstrap
        run: ./.github/r-ci.sh bootstrap

      - name: Dependencies
        run: ./.github/r-ci.sh install_all

      - name: Test
        run: ./.github/r-ci.sh run_tests

      - name: Coverage
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: ./.github/r-ci.sh coverage
