# Run CI for R based on copy of https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
  pull_request:

env:
  _R_CHECK_FORCE_SUGGESTS_: "FALSE"

jobs:
  ci:
    strategy:
      matrix:
        include:
          - {os: macOS-latest}
          - {os: ubuntu-latest}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: System
        run: sysctl -a
        if: ${{ matrix.os == 'macOS-latest' }}

      - name: Bootstrap
        run: ./.github/r-ci.sh bootstrap

      - name: Dependencies
        run: ./.github/r-ci.sh install_all

      - name: Test
        run: ./.github/r-ci.sh run_tests

      - name: Show install log
        run: cat $HOME/work/TileDB-R/TileDB-R/tiledb.Rcheck/00install.out
        if: failure()

      - name: Show test log
        run: cat $HOME/work/TileDB-R/TileDB-R/tiledb.Rcheck/00check.log
        if: failure()

      #- name: Coverage
      #  if: ${{ matrix.os == 'ubuntu-latest' }}
      #  run: ./.github/r-ci.sh coverage
