name: nightly

on:
  #schedule:
  #  - cron: "17 01 * * *"
  workflow_dispatch:
  push:

jobs:
  dev:
    runs-on: ubuntu-latest

    container:
      image: rocker/r2u:latest

    steps:
      - uses: actions/checkout@v4

      - name: SessionInfo
        run: R -q -e 'sessionInfo()'

      - name: System Dependencies
        # this particular package needs cmake and curl and git to build
        run: apt update -qq && apt install --yes --no-install-recommends cmake curl git

      - name: Package Dependencies
        run: R -q -e 'remotes::install_deps(".", dependencies=TRUE)'

      - name: Build Package
        run: R CMD build --no-build-vignettes --no-manual .

      - name: Install Package
        run: R CMD INSTALL --configure-args="--with-download=https://github.com/TileDB-Inc/TileDB/archive/refs/heads/dev.zip" $(ls -1tr *.tar.gz | tail -1)

      #- name: Check Package
      #  run: R CMD check --no-vignettes --no-manual $(ls -1tr *.tar.gz | tail -1)
