on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:
    name: (Windows/mingw-w64)
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install dependencies
        run: |
          setRepositories(ind = 1:2)
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = NA)
        shell: Rscript {0}
        env:
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_: false
          _R_CHECK_FORCE_SUGGESTS_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--no-vignettes", "--as-cran"), build_args = c("--no-build-vignettes"), error_on = "error", check_dir = "check")
        shell: Rscript {0}
