on:
  push:
  pull_request:

name: windows

jobs:
  windows:
    runs-on: ${{ matrix.windows }}
    strategy:
      fail-fast: false
      matrix:
        include: [
          { windows: windows-2019, r: release },
          { windows: windows-2022, r: devel },
          { windows: windows-2022, r: devel-ucrt }
        ]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r }}
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = NA)
          install.packages(c("palmerpenguins", "nycflights13", "tibble", "data.table"))
        shell: Rscript {0}
        env:
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_: false
          _R_CHECK_FORCE_SUGGESTS_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--no-vignettes", "--as-cran"), build_args = c("--no-build-vignettes"), error_on = "error", check_dir = "check")
        shell: Rscript {0}
